/* ============================================================
   study-data.js — verified card appendix for the study tool.

   TRUTHFULNESS RULE (do not break):
   Every card below traces to a fact already published and
   reviewed elsewhere on this site (feeder-monitor.html /
   learn.html / index.html) or to a textbook-standard electrical
   fundamental. The `source` field names where each fact comes
   from. Do NOT add cards for facts beyond these verified
   sources without checking with the user first. If a fact can't
   be sourced, leave it out — don't guess.
   ============================================================ */

var STUDY_CARDS = [

  /* ---- Measurement & Ohm's law ---- */
  { id: "ohm-1", category: "Measurement & Ohm's law",
    front: "State Ohm's law as a formula linking voltage, current and resistance.",
    back: "V = I × R. Voltage equals current multiplied by resistance.",
    source: "Textbook fundamental · feeder-monitor.html, Measurement & Ohm's law" },
  { id: "ohm-2", category: "Measurement & Ohm's law",
    front: "What is the formula for electrical power in terms of voltage and current?",
    back: "P = V × I. Power equals voltage multiplied by current.",
    source: "Textbook fundamental · feeder-monitor.html, Measurement & Ohm's law" },
  { id: "ohm-3", category: "Measurement & Ohm's law",
    front: "Rearrange V = I × R to solve for current.",
    back: "I = V ÷ R.",
    source: "Textbook fundamental" },
  { id: "ohm-4", category: "Measurement & Ohm's law",
    front: "Rearrange V = I × R to solve for resistance.",
    back: "R = V ÷ I.",
    source: "Textbook fundamental" },
  { id: "ohm-5", category: "Measurement & Ohm's law",
    front: "A 12 V supply drives a 6 Ω load. What current flows?",
    back: "I = V ÷ R = 12 ÷ 6 = 2 A.",
    source: "Worked from Ohm's law (computed)" },
  { id: "ohm-6", category: "Measurement & Ohm's law",
    front: "A load draws 2 A at 12 V. How much power does it dissipate?",
    back: "P = V × I = 12 × 2 = 24 W.",
    source: "Worked from the power formula (computed)" },
  { id: "ohm-7", category: "Measurement & Ohm's law",
    front: "How can you measure current using a shunt resistor instead of an ammeter?",
    back: "Measure the small voltage across a known shunt resistance, then work back to current with I = V ÷ R.",
    source: "feeder-monitor.html, Measurement & Ohm's law" },

  /* ---- Protection & earthing ---- */
  { id: "prot-1", category: "Protection & earthing",
    front: "What do circuit breakers and fuses do?",
    back: "They interrupt overload and short-circuit current, breaking the circuit before it overheats or is damaged.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-2", category: "Protection & earthing",
    front: "What does a protection relay do?",
    back: "It detects a fault condition and trips a circuit breaker to disconnect the affected circuit.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-3", category: "Protection & earthing",
    front: "What does an RCD protect against?",
    back: "Earth leakage. It trips when the current flowing out doesn't return on the neutral, which can mean a leakage path to earth or through a person.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-4", category: "Protection & earthing",
    front: "Why does earthing matter for protection to operate?",
    back: "Earthing gives fault current a return path, so a protective device carries enough current to trip within the required disconnection time.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-5", category: "Protection & earthing",
    front: "What is a typical maximum disconnection time for a final subcircuit rated 32 A or less?",
    back: "About 0.4 seconds.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-6", category: "Protection & earthing",
    front: "What's the difference between an overload and a short circuit?",
    back: "An overload is current above the rated value on an otherwise sound circuit; a short circuit is a fault that draws very high current through an unintended low-resistance path. Breakers and fuses interrupt both.",
    source: "Textbook fundamental · feeder-monitor.html, Protection & earthing" },

  /* ---- Grid structure ---- */
  { id: "grid-1", category: "Grid structure",
    front: "What voltages does Transgrid's high-voltage transmission network run at in NSW?",
    back: "Around 500 / 330 / 220 / 132 kV.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-2", category: "Grid structure",
    front: "Which three distribution businesses does Transgrid feed in NSW?",
    back: "Ausgrid, Endeavour Energy and Essential Energy.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-3", category: "Grid structure",
    front: "What does a zone substation do?",
    back: "It steps sub-transmission voltage down to roughly 11–22 kV.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-4", category: "Grid structure",
    front: "What does a distribution substation step the voltage down to?",
    back: "415 V three-phase / 230 V single-phase.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-5", category: "Grid structure",
    front: "What is a feeder in the distribution network?",
    back: "An 11–33 kV line running between substations.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-6", category: "Grid structure",
    front: "What traction voltage does Sydney Trains use, and what else does it run?",
    back: "1500 V DC traction, plus its own high-voltage network.",
    source: "feeder-monitor.html, NSW grid structure" },

  /* ---- Drawings & standards ---- */
  { id: "draw-1", category: "Drawings & standards",
    front: "What does a single-line diagram (SLD) represent with one line?",
    back: "A multi-conductor circuit: supply → main switch → protective devices → subcircuits, with the MEN link shown at the main switchboard and every circuit labelled.",
    source: "feeder-monitor.html, Single-line diagrams & wiring colours" },
  { id: "draw-2", category: "Drawings & standards",
    front: "Which standard defines the graphical symbols used on a single-line diagram?",
    back: "AS/NZS 60617. Keep to one symbol style and don't mix conventions.",
    source: "feeder-monitor.html, Single-line diagrams & wiring colours" },
  { id: "draw-3", category: "Drawings & standards",
    front: "Under AS/NZS 3000, what colour is the earth conductor?",
    back: "Green/yellow.",
    source: "AS/NZS 3000 · feeder-monitor.html, wiring colours" },
  { id: "draw-4", category: "Drawings & standards",
    front: "Under AS/NZS 3000, what colour is the neutral conductor?",
    back: "Blue.",
    source: "AS/NZS 3000 · feeder-monitor.html, wiring colours" },
  { id: "draw-5", category: "Drawings & standards",
    front: "Under AS/NZS 3000, what colour is the single-phase active (line) conductor?",
    back: "Brown (among the permitted colours).",
    source: "AS/NZS 3000 · feeder-monitor.html, wiring colours" },
  { id: "draw-6", category: "Drawings & standards",
    front: "What does MEN stand for, and where is the link shown?",
    back: "Multiple Earthed Neutral. The MEN link is shown at the main switchboard.",
    source: "Textbook fundamental · feeder-monitor.html, Single-line diagrams" },

  /* ---- Safety & isolation ---- */
  { id: "safe-1", category: "Safety & isolation",
    front: "List the safe-isolation sequence before working on equipment.",
    back: "Identify & notify → shut down & isolate → lock out & tag out → dissipate stored energy → prove dead (test before touch) → then work.",
    source: "feeder-monitor.html, Safety first (AS/NZS 4836)" },
  { id: "safe-2", category: "Safety & isolation",
    front: "Is a danger tag an isolation device?",
    back: "No. A tag is a warning; the lock provides the isolation. A tag is not an isolation device, the lock is.",
    source: "feeder-monitor.html, Safety first" },
  { id: "safe-3", category: "Safety & isolation",
    front: "What does 'prove dead' involve?",
    back: "Prove the tester on a known live source, test the circuit dead, then prove the tester live again: prove, test, prove.",
    source: "feeder-monitor.html, Safety first" },
  { id: "safe-4", category: "Safety & isolation",
    front: "Why isn't a functional on/off switch an isolation point?",
    back: "A functional switch isn't designed or rated as an energy-isolating device. You isolate at the proper isolating device and lock it off.",
    source: "feeder-monitor.html, Safety first" },
  { id: "safe-5", category: "Safety & isolation",
    front: "Which code of practice and regulation govern managing electrical risks at work in NSW?",
    back: "The SafeWork NSW 'Managing electrical risks in the workplace' Code of Practice, under WHS Regulation Part 4.7 (with AS/NZS 4836 for low-voltage safe working).",
    source: "feeder-monitor.html, Safety first" },
  { id: "safe-6", category: "Safety & isolation",
    front: "In NSW, what defines extra-low voltage (ELV)?",
    back: "At or below 50 V AC / 120 V DC. ELV is excluded from 'electrical installation', so a battery or USB rig that never touches fixed mains wiring isn't licensable electrical work under the Gas and Electricity (Consumer Safety) Act 2017 and its 2018 Regulation.",
    source: "feeder-monitor.html, Legal envelope" },

  /* ---- Trade & units (interview prep) ---- */
  { id: "unit-1", category: "Trade & units",
    front: "Which pre-apprenticeship unit covers applying WHS regulations, codes and practices?",
    back: "UEECD0007.",
    source: "index.html, Trade competencies" },
  { id: "unit-2", category: "Trade & units",
    front: "Which pre-apprenticeship unit covers fabricating, assembling and dismantling utilities components?",
    back: "UEECD0019.",
    source: "index.html, Trade competencies" },
  { id: "unit-3", category: "Trade & units",
    front: "Which pre-apprenticeship unit covers using drawings, diagrams, standards and specifications?",
    back: "UEECD0051.",
    source: "index.html, Trade competencies" }

];
