/* ============================================================
   study-data.js — verified card appendix for the study tool.

   TRUTHFULNESS RULE (do not break):
   Every card below traces to a fact already published and
   reviewed elsewhere on this site (feeder-monitor.html /
   learn.html / index.html) or to a textbook-standard electrical
   fundamental. The `source` field names where each fact comes
   from. Do NOT add cards for facts beyond these verified
   sources without checking with the user first. If a fact can't
   be sourced, leave it out — don't guess.
   ============================================================ */

var STUDY_CARDS = [

  /* ---- Measurement & Ohm's law ---- */
  { id: "ohm-1", category: "Measurement & Ohm's law",
    front: "State Ohm's law as a formula linking voltage, current and resistance.",
    back: "V = I × R. Voltage equals current multiplied by resistance.",
    source: "Textbook fundamental · feeder-monitor.html, Measurement & Ohm's law" },
  { id: "ohm-2", category: "Measurement & Ohm's law",
    front: "What is the formula for electrical power in terms of voltage and current?",
    back: "P = V × I. Power equals voltage multiplied by current.",
    source: "Textbook fundamental · feeder-monitor.html, Measurement & Ohm's law" },
  { id: "ohm-3", category: "Measurement & Ohm's law",
    front: "Rearrange V = I × R to solve for current.",
    back: "I = V ÷ R.",
    source: "Textbook fundamental" },
  { id: "ohm-4", category: "Measurement & Ohm's law",
    front: "Rearrange V = I × R to solve for resistance.",
    back: "R = V ÷ I.",
    source: "Textbook fundamental" },
  { id: "ohm-5", category: "Measurement & Ohm's law",
    front: "A 12 V supply drives a 6 Ω load. What current flows?",
    back: "I = V ÷ R = 12 ÷ 6 = 2 A.",
    source: "Worked from Ohm's law (computed)" },
  { id: "ohm-6", category: "Measurement & Ohm's law",
    front: "A load draws 2 A at 12 V. How much power does it dissipate?",
    back: "P = V × I = 12 × 2 = 24 W.",
    source: "Worked from the power formula (computed)" },
  { id: "ohm-7", category: "Measurement & Ohm's law",
    front: "How can you measure current using a shunt resistor instead of an ammeter?",
    back: "Measure the small voltage across a known shunt resistance, then work back to current with I = V ÷ R.",
    source: "feeder-monitor.html, Measurement & Ohm's law" },

  /* ---- Protection & earthing ---- */
  { id: "prot-1", category: "Protection & earthing",
    front: "What do circuit breakers and fuses do?",
    back: "They interrupt overload and short-circuit current, breaking the circuit before it overheats or is damaged.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-2", category: "Protection & earthing",
    front: "What does a protection relay do?",
    back: "It detects a fault condition and trips a circuit breaker to disconnect the affected circuit.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-3", category: "Protection & earthing",
    front: "What does an RCD protect against?",
    back: "Earth leakage. It trips when the current flowing out doesn't return on the neutral, which can mean a leakage path to earth or through a person.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-4", category: "Protection & earthing",
    front: "Why does earthing matter for protection to operate?",
    back: "Earthing gives fault current a return path, so a protective device carries enough current to trip within the required disconnection time.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-5", category: "Protection & earthing",
    front: "What is a typical maximum disconnection time for a final subcircuit rated 32 A or less?",
    back: "About 0.4 seconds.",
    source: "feeder-monitor.html, Protection & earthing" },
  { id: "prot-6", category: "Protection & earthing",
    front: "What's the difference between an overload and a short circuit?",
    back: "An overload is current above the rated value on an otherwise sound circuit; a short circuit is a fault that draws very high current through an unintended low-resistance path. Breakers and fuses interrupt both.",
    source: "Textbook fundamental · feeder-monitor.html, Protection & earthing" },

  /* ---- Grid structure ---- */
  { id: "grid-1", category: "Grid structure",
    front: "What voltages does Transgrid's high-voltage transmission network run at in NSW?",
    back: "Around 500 / 330 / 220 / 132 kV.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-2", category: "Grid structure",
    front: "Which three distribution businesses does Transgrid feed in NSW?",
    back: "Ausgrid, Endeavour Energy and Essential Energy.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-3", category: "Grid structure",
    front: "What does a zone substation do?",
    back: "It steps sub-transmission voltage down to roughly 11–22 kV.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-4", category: "Grid structure",
    front: "What does a distribution substation step the voltage down to?",
    back: "415 V three-phase / 230 V single-phase.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-5", category: "Grid structure",
    front: "What is a feeder in the distribution network?",
    back: "An 11–33 kV line running between substations.",
    source: "feeder-monitor.html, NSW grid structure" },
  { id: "grid-6", category: "Grid structure",
    front: "What traction voltage does Sydney Trains use, and what else does it run?",
    back: "1500 V DC traction, plus its own high-voltage network.",
    source: "feeder-monitor.html, NSW grid structure" },

  /* ---- Drawings & standards ---- */
  { id: "draw-1", category: "Drawings & standards",
    front: "What does a single-line diagram (SLD) represent with one line?",
    back: "A multi-conductor circuit: supply → main switch → protective devices → subcircuits, with the MEN link shown at the main switchboard and every circuit labelled.",
    source: "feeder-monitor.html, Single-line diagrams & wiring colours" },
  { id: "draw-2", category: "Drawings & standards",
    front: "Which standard defines the graphical symbols used on a single-line diagram?",
    back: "AS/NZS 60617. Keep to one symbol style and don't mix conventions.",
    source: "feeder-monitor.html, Single-line diagrams & wiring colours" },
  { id: "draw-3", category: "Drawings & standards",
    front: "Under AS/NZS 3000, what colour is the earth conductor?",
    back: "Green/yellow.",
    source: "AS/NZS 3000 · feeder-monitor.html, wiring colours" },
  { id: "draw-4", category: "Drawings & standards",
    front: "Under AS/NZS 3000, what colour is the neutral conductor?",
    back: "Blue.",
    source: "AS/NZS 3000 · feeder-monitor.html, wiring colours" },
  { id: "draw-5", category: "Drawings & standards",
    front: "Under AS/NZS 3000, what colour is the single-phase active (line) conductor?",
    back: "Brown (among the permitted colours).",
    source: "AS/NZS 3000 · feeder-monitor.html, wiring colours" },
  { id: "draw-6", category: "Drawings & standards",
    front: "What does MEN stand for, and where is the link shown?",
    back: "Multiple Earthed Neutral. The MEN link is shown at the main switchboard.",
    source: "Textbook fundamental · feeder-monitor.html, Single-line diagrams" },

  /* ---- Safety & isolation ---- */
  { id: "safe-1", category: "Safety & isolation",
    front: "List the safe-isolation sequence before working on equipment.",
    back: "Identify & notify → shut down & isolate → lock out & tag out → dissipate stored energy → prove dead (test before touch) → then work.",
    source: "feeder-monitor.html, Safety first (AS/NZS 4836)" },
  { id: "safe-2", category: "Safety & isolation",
    front: "Is a danger tag an isolation device?",
    back: "No. A tag is a warning; the lock provides the isolation. A tag is not an isolation device, the lock is.",
    source: "feeder-monitor.html, Safety first" },
  { id: "safe-3", category: "Safety & isolation",
    front: "What does 'prove dead' involve?",
    back: "Prove the tester on a known live source, test the circuit dead, then prove the tester live again: prove, test, prove.",
    source: "feeder-monitor.html, Safety first" },
  { id: "safe-4", category: "Safety & isolation",
    front: "Why isn't a functional on/off switch an isolation point?",
    back: "A functional switch isn't designed or rated as an energy-isolating device. You isolate at the proper isolating device and lock it off.",
    source: "feeder-monitor.html, Safety first" },
  { id: "safe-5", category: "Safety & isolation",
    front: "Which code of practice and regulation govern managing electrical risks at work in NSW?",
    back: "The SafeWork NSW 'Managing electrical risks in the workplace' Code of Practice, under WHS Regulation Part 4.7 (with AS/NZS 4836 for low-voltage safe working).",
    source: "feeder-monitor.html, Safety first" },
  { id: "safe-6", category: "Safety & isolation",
    front: "In NSW, what defines extra-low voltage (ELV)?",
    back: "At or below 50 V AC / 120 V DC. ELV is excluded from 'electrical installation', so a battery or USB rig that never touches fixed mains wiring isn't licensable electrical work under the Gas and Electricity (Consumer Safety) Act 2017 and its 2018 Regulation.",
    source: "feeder-monitor.html, Legal envelope" },

  /* ---- Trade & units (interview prep) ---- */
  { id: "unit-1", category: "Trade & units",
    front: "Which pre-apprenticeship unit covers applying WHS regulations, codes and practices?",
    back: "UEECD0007.",
    source: "index.html, Trade competencies" },
  { id: "unit-2", category: "Trade & units",
    front: "Which pre-apprenticeship unit covers fabricating, assembling and dismantling utilities components?",
    back: "UEECD0019.",
    source: "index.html, Trade competencies" },
  { id: "unit-3", category: "Trade & units",
    front: "Which pre-apprenticeship unit covers using drawings, diagrams, standards and specifications?",
    back: "UEECD0051.",
    source: "index.html, Trade competencies" },

  /* ===== Safety & WHS ===== */
  { id: "whs-1", category: "Safety & WHS", front: "What is the order of the hierarchy of controls?", back: "Elimination, substitution, isolation/engineering controls, administrative controls, then PPE last.", source: "WHS / SafeWork NSW" },
  { id: "whs-2", category: "Safety & WHS", front: "Where does PPE sit in the hierarchy of controls?", back: "Last. PPE is the lowest-order control, used when higher controls can't remove the risk.", source: "WHS / SafeWork NSW" },
  { id: "whs-3", category: "Safety & WHS", front: "What does PPE stand for?", back: "Personal Protective Equipment.", source: "WHS / SafeWork NSW" },
  { id: "whs-4", category: "Safety & WHS", front: "What does a JSA do?", back: "A Job Safety Analysis breaks a task into steps and identifies the hazards and controls for each.", source: "WHS / SafeWork NSW" },
  { id: "whs-5", category: "Safety & WHS", front: "What is a SWMS?", back: "A Safe Work Method Statement; required for high-risk construction work, it sets out hazards and controls.", source: "WHS / SafeWork NSW" },
  { id: "whs-6", category: "Safety & WHS", front: "If a workmate is in contact with a live source, what comes first?", back: "Isolate or switch off the supply before touching them, so you don't become a second casualty. Then call for help.", source: "SafeWork NSW guidance" },
  { id: "whs-7", category: "Safety & WHS", front: "What three factors decide how dangerous an electric shock is?", back: "The current magnitude, the path through the body, and how long the contact lasts.", source: "Textbook fundamental" },
  { id: "whs-8", category: "Safety & WHS", front: "At what residual current do RCDs for personal protection typically trip?", back: "About 30 mA.", source: "AS/NZS 3000 (Wiring Rules)" },
  { id: "whs-9", category: "Safety & WHS", front: "What does RCD stand for?", back: "Residual Current Device.", source: "AS/NZS 3000 (Wiring Rules)" },
  { id: "whs-10", category: "Safety & WHS", front: "How does an RCD detect a fault?", back: "It senses an imbalance between the active and neutral currents (leakage to earth) and disconnects.", source: "AS/NZS 3000 (Wiring Rules)" },
  { id: "whs-11", category: "Safety & WHS", front: "What is an RCBO?", back: "A combined device: RCD (earth-leakage) plus circuit breaker (overcurrent) in one.", source: "AS/NZS 3000 (Wiring Rules)" },
  { id: "whs-12", category: "Safety & WHS", front: "What is the purpose of lockout-tagout?", back: "To prevent equipment being inadvertently re-energised while someone is working on it.", source: "WHS / SafeWork NSW" },
  { id: "whs-13", category: "Safety & WHS", front: "What three things does a fire need (the fire triangle)?", back: "Heat, fuel and oxygen.", source: "Textbook fundamental" },
  { id: "whs-14", category: "Safety & WHS", front: "Why never use water on a live electrical fire?", back: "Water conducts electricity and creates a shock and spread risk. Use CO₂ or dry-powder extinguishers.", source: "SafeWork NSW guidance" },
  { id: "whs-15", category: "Safety & WHS", front: "What is an arc flash?", back: "An explosive release of energy from an electrical fault; controlled by isolation, distance and appropriate PPE.", source: "Textbook fundamental" },
  { id: "whs-16", category: "Safety & WHS", front: "Why is working de-energised the safest option?", back: "It eliminates the electrical hazard entirely rather than relying on lower-order controls.", source: "WHS / SafeWork NSW" },
  { id: "whs-17", category: "Safety & WHS", front: "What is the general duty of care under WHS law?", back: "Everyone must take reasonable care for their own safety and that of others affected by their work.", source: "WHS Act" },
  { id: "whs-18", category: "Safety & WHS", front: "What should you do when you spot a workplace hazard?", back: "Report it to your supervisor and, where safe, control or isolate it.", source: "WHS / SafeWork NSW" },
  { id: "whs-19", category: "Safety & WHS", front: "Name two controls for a manual-handling risk.", back: "Use mechanical aids or team lifting, and correct lifting technique; reduce the load or distance.", source: "WHS / SafeWork NSW" },
  { id: "whs-20", category: "Safety & WHS", front: "What does a White Card show?", back: "That the holder has completed general construction induction training. It is not a trade licence.", source: "SafeWork NSW" },

  /* ===== Wiring rules (AS/NZS 3000) ===== */
  { id: "wr-1", category: "Wiring rules", front: "What is the common name for AS/NZS 3000?", back: "The Wiring Rules.", source: "AS/NZS 3000" },
  { id: "wr-2", category: "Wiring rules", front: "What is the nominal single-phase supply voltage in Australia?", back: "230 V (nominal).", source: "AS/NZS 3000" },
  { id: "wr-3", category: "Wiring rules", front: "What is the nominal three-phase supply voltage in Australia?", back: "400 V line-to-line, 230 V line-to-neutral (nominal).", source: "AS/NZS 3000" },
  { id: "wr-4", category: "Wiring rules", front: "What is the supply frequency in Australia?", back: "50 Hz.", source: "AS/NZS 3000" },
  { id: "wr-5", category: "Wiring rules", front: "What does the MEN system link at the main switchboard?", back: "The neutral and earth are connected (Multiple Earthed Neutral).", source: "AS/NZS 3000" },
  { id: "wr-6", category: "Wiring rules", front: "What is the main purpose of earthing an installation?", back: "To give fault current a low-impedance path so protection operates, and to keep exposed metal at a safe potential.", source: "AS/NZS 3000" },
  { id: "wr-7", category: "Wiring rules", front: "What is equipotential bonding?", back: "Connecting metal parts together so they sit at the same electrical potential, reducing shock risk.", source: "AS/NZS 3000" },
  { id: "wr-8", category: "Wiring rules", front: "What does an IP rating describe?", back: "Ingress Protection: the first digit rates protection against solids/dust, the second against water.", source: "AS/NZS / IEC 60529" },
  { id: "wr-9", category: "Wiring rules", front: "What does Class II (double-insulated) equipment rely on instead of an earth?", back: "Two independent layers of insulation; it needs no protective earth connection.", source: "Textbook fundamental" },
  { id: "wr-10", category: "Wiring rules", front: "What does Class I equipment rely on for protection?", back: "A protective earth connection to exposed conductive parts.", source: "Textbook fundamental" },
  { id: "wr-11", category: "Wiring rules", front: "Why must circuit protection match the cable's current rating?", back: "So the protective device trips before the cable overheats; protection is sized to protect the cable.", source: "AS/NZS 3000" },
  { id: "wr-12", category: "Wiring rules", front: "What does the main switch on a switchboard do?", back: "It isolates the whole installation from the supply.", source: "AS/NZS 3000" },
  { id: "wr-13", category: "Wiring rules", front: "Why is correct polarity tested before energising?", back: "To confirm active, neutral and earth are connected to the right terminals, which is essential for safety.", source: "AS/NZS 3000" },
  { id: "wr-14", category: "Wiring rules", front: "What is the purpose of conduit?", back: "Mechanical protection and containment/routing of cables.", source: "Textbook fundamental" },
  { id: "wr-15", category: "Wiring rules", front: "Name three factors that derate a cable's current capacity.", back: "Grouping with other cables, higher ambient temperature, and the insulation type/installation method.", source: "AS/NZS 3008" },
  { id: "wr-16", category: "Wiring rules", front: "Why observe a cable's minimum bending radius?", back: "Bending tighter than the minimum can damage the insulation and conductors.", source: "Textbook fundamental" },
  { id: "wr-17", category: "Wiring rules", front: "What is the historical (pre-harmonised) AU active conductor colour?", back: "Red (active), black (neutral), green (earth). Modern colours are brown, blue and green/yellow.", source: "AS/NZS 3000 (historical vs current)" },

  /* ===== DC fundamentals ===== */
  { id: "dc-1", category: "DC fundamentals", front: "State Kirchhoff's Current Law.", back: "The total current into a node equals the total current out of it (charge is conserved).", source: "Textbook fundamental" },
  { id: "dc-2", category: "DC fundamentals", front: "State Kirchhoff's Voltage Law.", back: "Around any closed loop, the voltages sum to zero (rises equal drops).", source: "Textbook fundamental" },
  { id: "dc-3", category: "DC fundamentals", front: "In a series circuit, what is the same through every component?", back: "The current.", source: "Textbook fundamental" },
  { id: "dc-4", category: "DC fundamentals", front: "In a series circuit, how do the component voltages relate to the supply?", back: "They add up to the supply voltage.", source: "Textbook fundamental" },
  { id: "dc-5", category: "DC fundamentals", front: "In a parallel circuit, what is the same across every branch?", back: "The voltage.", source: "Textbook fundamental" },
  { id: "dc-6", category: "DC fundamentals", front: "In a parallel circuit, how do branch currents relate to the total?", back: "The branch currents add up to the total supply current.", source: "Textbook fundamental" },
  { id: "dc-7", category: "DC fundamentals", front: "How does total parallel resistance compare to the smallest branch?", back: "It is always less than the smallest individual branch resistance.", source: "Textbook fundamental" },
  { id: "dc-8", category: "DC fundamentals", front: "What is a conductor?", back: "A material that allows current to flow easily, such as copper or aluminium.", source: "Textbook fundamental" },
  { id: "dc-9", category: "DC fundamentals", front: "What is an insulator?", back: "A material that strongly resists current flow, such as PVC, rubber or glass.", source: "Textbook fundamental" },
  { id: "dc-10", category: "DC fundamentals", front: "How does a conductor's length affect its resistance?", back: "Longer conductors have higher resistance.", source: "Textbook fundamental" },
  { id: "dc-11", category: "DC fundamentals", front: "How does cross-sectional area affect resistance?", back: "A larger cross-section gives lower resistance.", source: "Textbook fundamental" },
  { id: "dc-12", category: "DC fundamentals", front: "How does temperature affect the resistance of most metals?", back: "Resistance increases as temperature rises.", source: "Textbook fundamental" },
  { id: "dc-13", category: "DC fundamentals", front: "Which conducts better for the same size: copper or aluminium?", back: "Copper has lower resistivity, so it conducts better than aluminium of the same size.", source: "Textbook fundamental" },
  { id: "dc-14", category: "DC fundamentals", front: "Which way does conventional current flow?", back: "From positive to negative (electron flow is the opposite direction).", source: "Textbook fundamental" },
  { id: "dc-15", category: "DC fundamentals", front: "What is EMF?", back: "Electromotive force: the voltage produced by a source such as a battery or generator.", source: "Textbook fundamental" },
  { id: "dc-16", category: "DC fundamentals", front: "What is potential difference?", back: "The voltage between two points in a circuit.", source: "Textbook fundamental" },
  { id: "dc-17", category: "DC fundamentals", front: "What is electrical power?", back: "The rate at which energy is transferred or converted, measured in watts.", source: "Textbook fundamental" },
  { id: "dc-18", category: "DC fundamentals", front: "Define charge in terms of current and time.", back: "Q = I × t: one coulomb is one amp flowing for one second.", source: "Textbook fundamental" },
  { id: "dc-19", category: "DC fundamentals", front: "What do batteries in series increase?", back: "The total voltage (capacities/current capability stay the same).", source: "Textbook fundamental" },
  { id: "dc-20", category: "DC fundamentals", front: "What do identical batteries in parallel increase?", back: "The current capacity (the voltage stays the same).", source: "Textbook fundamental" },

  /* ===== AC fundamentals ===== */
  { id: "ac-1", category: "AC fundamentals", front: "What is alternating current (AC)?", back: "Current that periodically reverses direction.", source: "Textbook fundamental" },
  { id: "ac-2", category: "AC fundamentals", front: "What is direct current (DC)?", back: "Current that flows in one direction only.", source: "Textbook fundamental" },
  { id: "ac-3", category: "AC fundamentals", front: "What is the period of a 50 Hz waveform?", back: "20 ms (period = 1 ÷ frequency = 1 ÷ 50).", source: "Textbook fundamental" },
  { id: "ac-4", category: "AC fundamentals", front: "What does the RMS value of an AC waveform represent?", back: "The equivalent DC value that delivers the same heating power.", source: "Textbook fundamental" },
  { id: "ac-5", category: "AC fundamentals", front: "For a sine wave, how is RMS related to peak?", back: "Vrms = Vpeak ÷ √2 ≈ 0.707 × Vpeak.", source: "Textbook fundamental" },
  { id: "ac-6", category: "AC fundamentals", front: "For a sine wave, how is peak related to RMS?", back: "Vpeak = √2 × Vrms ≈ 1.414 × Vrms (so 230 V RMS ≈ 325 V peak).", source: "Textbook fundamental" },
  { id: "ac-7", category: "AC fundamentals", front: "How far apart are the phases in a three-phase supply?", back: "120 degrees.", source: "Textbook fundamental" },
  { id: "ac-8", category: "AC fundamentals", front: "What is a key advantage of AC over DC for supply?", back: "AC voltage is easily changed up or down with transformers.", source: "Textbook fundamental" },
  { id: "ac-9", category: "AC fundamentals", front: "What is power factor?", back: "The ratio of real power (W) to apparent power (VA).", source: "Textbook fundamental" },
  { id: "ac-10", category: "AC fundamentals", front: "Give the units of real, apparent and reactive power.", back: "Real power in watts (W), apparent power in volt-amperes (VA), reactive power in VAR.", source: "Textbook fundamental" },
  { id: "ac-11", category: "AC fundamentals", front: "What kind of power factor do motors (inductive loads) cause?", back: "A lagging power factor.", source: "Textbook fundamental" },
  { id: "ac-12", category: "AC fundamentals", front: "What is impedance?", back: "The total opposition to AC current (resistance plus reactance), measured in ohms.", source: "Textbook fundamental" },
  { id: "ac-13", category: "AC fundamentals", front: "What is the unit of frequency?", back: "Hertz (Hz), cycles per second.", source: "Textbook fundamental" },
  { id: "ac-14", category: "AC fundamentals", front: "In a purely resistive AC circuit, how do voltage and current relate?", back: "They are in phase.", source: "Textbook fundamental" },
  { id: "ac-15", category: "AC fundamentals", front: "In a star-connected three-phase system, how does line voltage relate to phase voltage?", back: "VL = √3 × Vphase (about 1.732 times).", source: "Textbook fundamental" },
  { id: "ac-16", category: "AC fundamentals", front: "Why is electricity transmitted at high voltage?", back: "Higher voltage means lower current for the same power, which cuts I²R losses in the lines.", source: "Textbook fundamental" },
  { id: "ac-17", category: "AC fundamentals", front: "What does a capacitor do in a circuit?", back: "Stores energy in an electric field and opposes a change in voltage; used for power-factor correction.", source: "Textbook fundamental" },
  { id: "ac-18", category: "AC fundamentals", front: "What does an inductor do in a circuit?", back: "Stores energy in a magnetic field and opposes a change in current.", source: "Textbook fundamental" },

  /* ===== Magnetism & induction ===== */
  { id: "mag-1", category: "Magnetism & induction", front: "How do magnetic poles interact?", back: "Like poles repel; unlike poles attract.", source: "Textbook fundamental" },
  { id: "mag-2", category: "Magnetism & induction", front: "What surrounds a current-carrying conductor?", back: "A magnetic field.", source: "Textbook fundamental" },
  { id: "mag-3", category: "Magnetism & induction", front: "State Faraday's law of induction in plain terms.", back: "A changing magnetic field through a conductor induces a voltage in it.", source: "Textbook fundamental" },
  { id: "mag-4", category: "Magnetism & induction", front: "State Lenz's law.", back: "An induced current flows in the direction that opposes the change producing it.", source: "Textbook fundamental" },
  { id: "mag-5", category: "Magnetism & induction", front: "What principle lets a transformer work without moving parts?", back: "Mutual induction between two windings via a shared changing magnetic flux.", source: "Textbook fundamental" },
  { id: "mag-6", category: "Magnetism & induction", front: "What is a solenoid?", back: "A coil that produces a magnetic field when current flows through it.", source: "Textbook fundamental" },
  { id: "mag-7", category: "Magnetism & induction", front: "How can you strengthen an electromagnet?", back: "More turns, more current, or an iron core.", source: "Textbook fundamental" },
  { id: "mag-8", category: "Magnetism & induction", front: "How does a relay switch its contacts?", back: "An electromagnet pulls the contacts open or closed.", source: "Textbook fundamental" },
  { id: "mag-9", category: "Magnetism & induction", front: "Why are transformer and motor cores laminated?", back: "To reduce eddy-current losses in the core.", source: "Textbook fundamental" },
  { id: "mag-10", category: "Magnetism & induction", front: "What is back-EMF in a motor?", back: "A voltage the spinning motor generates that opposes the supply voltage.", source: "Textbook fundamental" },

  /* ===== Machines ===== */
  { id: "mc-1", category: "Machines", front: "What does a transformer do?", back: "Transfers energy between circuits by magnetic coupling and changes the voltage.", source: "Textbook fundamental" },
  { id: "mc-2", category: "Machines", front: "What is a step-up transformer?", back: "One with more secondary turns than primary, so the secondary voltage is higher.", source: "Textbook fundamental" },
  { id: "mc-3", category: "Machines", front: "In an ideal transformer, how do input and output power compare?", back: "They are equal: Vp × Ip = Vs × Is.", source: "Textbook fundamental" },
  { id: "mc-4", category: "Machines", front: "In a step-up transformer, what happens to the current?", back: "If the voltage goes up, the current goes down (power is conserved).", source: "Textbook fundamental" },
  { id: "mc-5", category: "Machines", front: "Why do transformers only work on AC?", back: "They need a continually changing magnetic flux; steady DC produces no induced secondary voltage.", source: "Textbook fundamental" },
  { id: "mc-6", category: "Machines", front: "What does an electric motor convert?", back: "Electrical energy into mechanical energy.", source: "Textbook fundamental" },
  { id: "mc-7", category: "Machines", front: "What does a generator convert?", back: "Mechanical energy into electrical energy.", source: "Textbook fundamental" },
  { id: "mc-8", category: "Machines", front: "Why is a three-phase induction motor self-starting?", back: "The three phases create a rotating magnetic field that drags the rotor around.", source: "Textbook fundamental" },
  { id: "mc-9", category: "Machines", front: "What sets an induction motor's synchronous speed?", back: "The supply frequency and the number of poles.", source: "Textbook fundamental" },
  { id: "mc-10", category: "Machines", front: "What is 'slip' in an induction motor?", back: "The difference between the synchronous speed and the actual rotor speed.", source: "Textbook fundamental" },
  { id: "mc-11", category: "Machines", front: "Why use star-delta starting on a large motor?", back: "To reduce the heavy starting current.", source: "Textbook fundamental" },
  { id: "mc-12", category: "Machines", front: "What does a commutator do in a DC machine?", back: "Reverses the current in the armature so torque stays in one direction.", source: "Textbook fundamental" },
  { id: "mc-13", category: "Machines", front: "What information is on a motor nameplate?", back: "Rated voltage, current, power, speed and other operating data.", source: "Textbook fundamental" },

  /* ===== Measurement & tools ===== */
  { id: "ms-1", category: "Measurement & tools", front: "What three quantities does a basic multimeter measure?", back: "Voltage, current and resistance.", source: "Textbook fundamental" },
  { id: "ms-2", category: "Measurement & tools", front: "How is a voltmeter connected?", back: "In parallel with the component being measured.", source: "Textbook fundamental" },
  { id: "ms-3", category: "Measurement & tools", front: "How is an ammeter connected?", back: "In series with the circuit so all the current flows through it.", source: "Textbook fundamental" },
  { id: "ms-4", category: "Measurement & tools", front: "What is the advantage of a clamp meter?", back: "It measures current around a single conductor without breaking the circuit.", source: "Textbook fundamental" },
  { id: "ms-5", category: "Measurement & tools", front: "On what kind of circuit do you measure resistance?", back: "A de-energised (dead) circuit only.", source: "Textbook fundamental" },
  { id: "ms-6", category: "Measurement & tools", front: "What does a megohmmeter (insulation tester) check?", back: "Insulation resistance, by applying a high test voltage.", source: "Textbook fundamental" },
  { id: "ms-7", category: "Measurement & tools", front: "Why must a test instrument be proven before use?", back: "To confirm it works, by testing it on a known live source (prove-test-prove).", source: "feeder-monitor.html, Safety first" },
  { id: "ms-8", category: "Measurement & tools", front: "Why does an ideal voltmeter have very high resistance?", back: "So it draws almost no current and doesn't disturb the circuit it measures.", source: "Textbook fundamental" },
  { id: "ms-9", category: "Measurement & tools", front: "Why does an ideal ammeter have very low resistance?", back: "So it adds negligible resistance to the circuit it is measuring.", source: "Textbook fundamental" },
  { id: "ms-10", category: "Measurement & tools", front: "Why must you never connect an ammeter across a supply?", back: "Its low resistance would create a short circuit.", source: "Textbook fundamental" },
  { id: "ms-11", category: "Measurement & tools", front: "What does a meter's CAT rating indicate?", back: "The measurement category/energy environment it is safely rated for.", source: "Textbook fundamental" },
  { id: "ms-12", category: "Measurement & tools", front: "What does a continuity test check?", back: "That there is an unbroken low-resistance path between two points.", source: "Textbook fundamental" },

  /* ===== Materials & cables ===== */
  { id: "mat-1", category: "Materials & cables", front: "What is the most common conductor metal in building wiring?", back: "Copper.", source: "Textbook fundamental" },
  { id: "mat-2", category: "Materials & cables", front: "Why is aluminium often used for overhead power lines?", back: "It is lighter and cheaper than copper for the same job.", source: "Textbook fundamental" },
  { id: "mat-3", category: "Materials & cables", front: "Name a common cable insulation material.", back: "PVC (polyvinyl chloride); XLPE is used where higher temperatures are expected.", source: "Textbook fundamental" },
  { id: "mat-4", category: "Materials & cables", front: "How is cable size specified?", back: "By conductor cross-sectional area in mm².", source: "Textbook fundamental" },
  { id: "mat-5", category: "Materials & cables", front: "Why is stranded cable used instead of solid?", back: "It is more flexible and easier to route.", source: "Textbook fundamental" },
  { id: "mat-6", category: "Materials & cables", front: "Which carries more current: a larger or smaller cross-section?", back: "A larger cross-section carries more current.", source: "Textbook fundamental" },
  { id: "mat-7", category: "Materials & cables", front: "What advantage does XLPE insulation have over PVC?", back: "It withstands a higher operating temperature.", source: "Textbook fundamental" },
  { id: "mat-8", category: "Materials & cables", front: "What does armoured cable provide?", back: "Mechanical protection for the conductors.", source: "Textbook fundamental" },

  /* ===== Electrical formulas (recall) ===== */
  { id: "fm-1", category: "Electrical formulas", front: "Formula linking voltage, current and resistance?", back: "V = I × R (Ohm's law).", source: "Textbook fundamental" },
  { id: "fm-2", category: "Electrical formulas", front: "Formula for power from voltage and current?", back: "P = V × I.", source: "Textbook fundamental" },
  { id: "fm-3", category: "Electrical formulas", front: "Formula for power from current and resistance?", back: "P = I² × R.", source: "Textbook fundamental" },
  { id: "fm-4", category: "Electrical formulas", front: "Formula for power from voltage and resistance?", back: "P = V² ÷ R.", source: "Textbook fundamental" },
  { id: "fm-5", category: "Electrical formulas", front: "Formula for electrical energy?", back: "E = P × t.", source: "Textbook fundamental" },
  { id: "fm-6", category: "Electrical formulas", front: "Formula for electric charge?", back: "Q = I × t.", source: "Textbook fundamental" },
  { id: "fm-7", category: "Electrical formulas", front: "Total resistance of resistors in series?", back: "Rₜ = R₁ + R₂ + R₃ + …", source: "Textbook fundamental" },
  { id: "fm-8", category: "Electrical formulas", front: "Total resistance of two resistors in parallel?", back: "Rₜ = (R₁ × R₂) ÷ (R₁ + R₂).", source: "Textbook fundamental" },
  { id: "fm-9", category: "Electrical formulas", front: "Transformer voltage/turns relationship?", back: "Vp ÷ Vs = Np ÷ Ns.", source: "Textbook fundamental" },
  { id: "fm-10", category: "Electrical formulas", front: "RMS of a sine wave from its peak?", back: "Vrms = Vpeak ÷ √2.", source: "Textbook fundamental" },
  { id: "fm-11", category: "Electrical formulas", front: "Three-phase star line-to-phase voltage relationship?", back: "VL = √3 × Vphase.", source: "Textbook fundamental" },
  { id: "fm-12", category: "Electrical formulas", front: "Power factor as a ratio?", back: "Power factor = real power (W) ÷ apparent power (VA).", source: "Textbook fundamental" }

];
